version: "3.9"

services:
  db-dev:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_dev
    ports:
      - "5432:5432"
    #volumes:
      #- db-data-dev:/var/lib/postgresql/data
    profiles:
      - dev

  db-prod:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_prod
    ports:
      - "5433:5432"
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    profiles:
      - prod

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db-dev:5432/inventory_dev}
      AUTH_DISABLED: ${AUTH_DISABLED:-true}
      ENVIRONMENT: dev
    volumes:
      - ./backend:/code
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db-dev
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db-prod:5432/inventory_prod}
      AUTH_DISABLED: "false"
      ENVIRONMENT: prod
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    ports:
      - "8000:8000"
    depends_on:
      - db-prod
    profiles:
      - prod

  frontend-dev:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    profiles:
      - dev

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://backend-prod:8000}
    ports:
      - "4173:4173"
    depends_on:
      - backend-prod
    profiles:
      - prod

volumes:
  db-data-dev:
  db-data-prod:
